version: '3.0'
services: 
    app: 
        image: 'tr4p3r/ci.test'
        volumes: 
            - '.:/var/www/html'
        networks: 
            - ci4
        ports: 
            - '80:8000'
        depends_on: 
            - mysql

    mysql:
        image: 'mysql:8.0'
        ports: 
            - '3306:3306'
        environment: 
            MYSQL_ROOT_PASSWORD: 'toor'
            MYSQL_DATABASE: 'ci4'
            MYSQL_USER: 'ci4'
            MYSQL_PASSWORD: 'password'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes' 
        volumes: 
            - 'ci4mysql:/var/lib/mysql'
        networks: 
            - ci4
        healthcheck:
            test: ["CMD", "mysqladmin", "ping"]

networks: 
    ci4:
        driver: bridge

volumes: 
    ci4mysql:
        driver: local
        